### ISSUE TITLE
Inconsistent line ending in genesis files

### ISSUE THREAD

**Issue by tmarkovski** [Indicio-tech/indicio-network#15]
Files under `genesis_files` have different line endings. Some are using CRLF while others use LF. Different library versions respond differently to this, with some (maybe older) versions throwing an error when CRLF is used.

**Comment by lynnbendixsen** [comment]
Thanks for the feedback!  We'll get that switched asap.  @GavinBendixsen

**Comment by lynnbendixsen** [comment]
I have finally fixed this in a PR and am awaiting approval and merging.  Thanks again for letting us know @tmarkovski !
https://github.com/Indicio-tech/indicio-network/pull/16

**Comment by lynnbendixsen** [comment]
PR is finally merged.  Thanks again! @tmarkovski
